### PR TITLE
Fix for #23 and #25

### PR DESCRIPTION
**Pull request by vnijs**
My main goal was to address #25. By adding `actionButton` characteristics to `shinyFilesButton` the `observe` created by `shinyFileChoose` now isn't activated until the button is clicked. With this PR the example below will illustrate that the file browser is populated when `shinyFilesButton` is specified in the UI but also with renderUI. I expect it would be straight forward to apply a similar approach for selecting a folder and saving files.

I added `if (updateFreq > 0) invalidateLater(updateFreq, session)` to the `shinyFilesChoose` function so the user can set `updateFreq` to 0 when calling this function and deactivate `invalidateLater` if desired.

I commented-out all lines with `Shiny.unbindAll();` or `Shiny.bindAll();` in `shinyFiles.js`. Without this change, the approach described above does *not* work. Finally, I removed legacy code from `shinyFiles.js` as I expect this is no longer required.

cc @thercast

```r
library(shiny)
library(shinyFiles)

# options(shiny.trace = TRUE)

shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(
        shinyFilesButton("loadFile", "Load a file", "Load a file", multiple = FALSE),
        uiOutput("loadFileOutPut")
      ),
      mainPanel()
    )
  ), 
  server = function(input, output, session) {
      
    shinyFileChoose(input = input, id = "loadFile", updateFreq = 0, session = session, roots = c( "project" = getwd()))
    shinyFileChoose(input = input, id = "loadFileUI", updateFreq = 0, session = session, roots = c( "project" = getwd()))
    
    output$loadFileOutPut <- renderUI({
      shinyFilesButton( "loadFileUI", "Load a file (renderUI)", "Load a file", multiple = FALSE )
    })
  }
)
```

### CODE REVIEW

**Comment by thercast** [comment]
@vnijs Looks great!  This greatly simplifies the code and all looks logical to me.

**Comment by thomasp85** [comment]
It seems weird that remove bindAll/unbindAll doesn’t make it break..? Maybe something has happened to Shiny since I wrote it...

I’ll test it tomorrow

**Comment by vnijs** [comment]
@thomasp85 I'm not sure if there were changes in Shiny. This may just be due to the fact that `*Buttons` in `shinyFiles` now have class `action-button` and Shiny handles binding and unbinding as needed.

I extended the approach used in filechoose.R to dirchoose.R and filesave.R and it seems to work well for both UI and renderUI. See extended example below. I don't use modules so can't say if it works there.

The latest commit also fixes #71. Month numbers, oddly, start at 0 in javascript so months (and therefore days) were off.

@thercast Since you mentioned you use shinyFiles in production it would be great if you could test the changes as well. You can install from my fork at https://github.com/vnijs/shinyFiles for now

@thomasp85 How do you feel about setting `updateFreq` to 0 by default? The file list is now already updated when the user clicks a `*Button` again. With the current default (2000 ms) in apps with a lot of `shinyFiles` buttons there would be *lots* of scans of the file system that, for most users, are probably not needed.

Also, how do you feel about running https://github.com/r-lib/styler on the R code and replacing tabs by (2) spaces throughout? The style in this package looks quite different from your (excellent!) recent `patchwork` for example.

```r
library(shiny)
library(shinyFiles)

# options(shiny.trace = TRUE)

shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(
        shinyFilesButton("loadFile", "Load a file", "Load a file", multiple = TRUE),
        uiOutput("loadFileOutput"),
        shinyDirButton("selectDir", "Folder select", "Please select a folder"),
        uiOutput("selectDirOutput"),
        shinySaveButton("saveFile", "Save file", "Save file as ...", filetype = list(text = "txt", picture = c("jpeg", "jpg"))),
        uiOutput("saveFileOutput")
      ),
      mainPanel(
        verbatimTextOutput("pathLoadFile"),
        verbatimTextOutput("pathLoadFileUI"),
        verbatimTextOutput("pathSelectDir"),
        verbatimTextOutput("pathSelectDirUI"),
        verbatimTextOutput("pathSaveFile"),
        verbatimTextOutput("pathSaveFileUI")
      )
    )
  ),
  server = function(input, output, session) {
    volumes <- c("Project" = getwd())

    shinyFileChoose(input = input, id = "loadFile", updateFreq = 0, session = session, roots = volumes)
    shinyFileChoose(input = input, id = "loadFileUI", updateFreq = 0, session = session, roots = volumes)
    shinyDirChoose(input, "selectDir", roots = volumes, session = session)
    shinyDirChoose(input, "selectDirUI", roots = volumes, session = session)
    shinyFileSave(input, "saveFile", roots = volumes, session = session)
    shinyFileSave(input, "saveFileUI", roots = volumes, session = session)

    output$loadFileOutput <- renderUI({
      shinyFilesButton("loadFileUI", "Load a file (renderUI)", "Load a file", multiple = TRUE)
    })
    output$selectDirOutput <- renderUI({
      shinyDirButton("selectDirUI", "Folder select (renderUI)", "Please select a folder")
    })
    output$saveFileOutput <- renderUI({
      shinySaveButton("saveFileUI", "Save file (renderUI)", "Save file as ...", filetype = list(text = "txt", picture = c("jpeg", "jpg")))
    })
    output$pathLoadFile <- renderPrint({
      parseFilePaths(volumes, input$loadFile)
    })
    output$pathLoadFileUI <- renderPrint({
      parseFilePaths(volumes, input$loadFileUI)
    })
    output$pathSelectDir <- renderPrint({
      parseDirPath(volumes, input$selectDir)
    })
    output$pathSelectDirUI <- renderPrint({
      parseDirPath(volumes, input$selectDirUI)
    })
    output$pathSaveFile <- renderPrint({
      parseSavePath(volumes, input$saveFile)
    })
    output$pathSaveFileUI <- renderPrint({
      parseSavePath(volumes, input$saveFileUI)
    })
  }
)
```

**Comment by thomasp85** [comment]
Great work - I’m fine with changing updateFreq. It’s a pretty costly operation... 

Styling could def be improved. This package is from my young and restless period where I haven’t really found my own voice😛 so the styling is all over the place. That being said I’d rather have that in a separate PR so it remains clear what is changed in this one (we can fold the #71 into this PR but I would prefer one PR per issue in general)

**Comment by vnijs** [comment]
Great! I would also prefer to make separate PRs. However, new commits just get added to the old one :) I haven't done a lot of PRs for repos managed by others. Do you have to a make a separate fork or branch to make that work?

**Comment by thercast** [comment]
I just tested it within a simple shiny module and it worked perfectly.  The module simply let the user select a csv file for importing in the session with `readr::read_csv()`.

**Comment by vnijs** [comment]
Thanks for testing with modules @thercast. I just posted some [ideas / TODOs](https://github.com/thomasp85/shinyFiles/issues/75). For example, it seems like a good idea that shinySaveButton allow filetype options to be updated based on user input in the app. I have a first attempt for this working, however, when the user changes the type (e.g., from rda to csv), the list of files shown in the modal is empty (binding - unbinding issue?). 

Have either of you tried something like this and had success? If so, does that still work now with the changes? I'm guessing that you probably couldn't do something like this before because shinyFiles didn't work with renderUI

**Comment by vnijs** [comment]
See [#25](https://github.com/thomasp85/shinyFiles/issues/25#issuecomment-399823565) for a reproducible example where renderUI still fails. Not sure how to fix this. Perhaps use the structure for custom inputs laid out in https://shiny.rstudio.com/articles/building-inputs.html?

**Comment by vnijs** [comment]
I tried adding an `updateShinySaveButton` function to change characteristics of the `shinySaveButton` (see below). I'm able to change the button label at least but not any of the characteristics of the file browser / modal (e.g., file types). The changes are not passed on to `saveFileUI-modal`

```r
library(shiny)
library(shinyFiles)

options(shiny.trace = TRUE)

formatFiletype <- function(filetype) {
    if(!is.na(filetype) && !is.null(filetype)) {
        filetype <- lapply(1:length(filetype), function(i) {
            list(name=names(filetype)[i], ext=I(filetype[[i]]))
        })
    }
    jsonlite::toJSON(filetype)
}

updateShinySaveButton <- function(
    session, inputId, label = NULL, title = NULL, 
    filetype = NULL, buttonType = NULL, 
    class = NULL, icon = NULL
) {
    if (is.null(filetype)) filetype <- NA
    filetype <- formatFiletype(filetype)
    
    dropNulls <- function(x) x[!vapply(x, is.null, FUN.VALUE = logical(1))]
    
    message <- list(
        label = label, 
        title = title, 
        filetype = filetype, 
        buttonType = buttonType, class = class, 
        icon = icon, id = inputId
    )
    message <- dropNulls(message)
    session$sendInputMessage(inputId, message)
}

shinyApp(
    ui = fluidPage(
        sidebarLayout(
            sidebarPanel(
                uiOutput("saveFileOutput"),
                selectInput("filetype", "Choose file type", c("csv", "txt", "rda")),
                selectInput("buttonlabel", "Button label", c("Save file ...", "Save file alt ...", "Save file another ..."))
            ),
            mainPanel()
        )
    ),
    server = function(input, output, session) {
        volumes <- c("Project" = getwd())
        
        shinyFileSave(input, "saveFileUI", roots = volumes, session = session)
        
        output$saveFileOutput <- renderUI({
            # shinySaveButton("saveFileUI", "Save file (renderUI)", "Save file as ...", filetype = input$filetype)
            shinySaveButton("saveFileUI", "Save file (renderUI)", "Save file as ...", filetype = list(filetypes = c("csv", "txt", "rda")))
        })
        
        observeEvent(input$filetype, {
            updateShinySaveButton(session, "saveFileUI", filetype = list(filetypes = input$filetype))
        })
        
        observeEvent(input$buttonlabel, {
            updateShinySaveButton(session, "saveFileUI", label = input$buttonlabel, title = input$buttonlabel)
        })
    }
)
```

**Comment by vnijs** [comment]
With this update using `renderUI` with `shinyFiles` actually seems to work :) The approach is, basically, to resend the file / directory when a `shinyFiles` button is selected. Although with smart caching you might be able to get a (slight) efficiency gain it causes added complexity and issues. This PR also pretty much alleviates the need to use `updateFreq`. The only if you want to continuously update the file / directory information when changes are made *outside* of a `shinyFiles` does this seem useful. Should we deprecate this argument?

To test the PR you can install from https://github.com/vnijs/shinyFiles. Looking forward to your comments.

cc @keqiang, @bbritten, @thercast 

```r
library(shiny)
library(shinyFiles)

# options(shiny.trace = TRUE)

shinyApp(
    ui = fluidPage(
        sidebarLayout(
            sidebarPanel(
                uiOutput("saveFileOutput"),
                uiOutput("loadFileOutput"),
                uiOutput("selectDirOutput"),
                selectInput("filetype", "Choose file type", c("csv", "txt", "rda", "R")),
                selectInput("buttonlabel", "Button label", c("Save file ...", "Save file alt ...", "Save file another ..."))
            ),
            mainPanel()
        )
    ),
    server = function(input, output, session) {
        volumes <- c("Project" = getwd())
        
        shinyFileSave(input, "saveFileUI", roots = volumes, session = session)
        shinyDirChoose(input, "selectDirUI", roots = volumes, session = session)
        
        output$saveFileOutput <- renderUI({
            shinySaveButton("saveFileUI", "Save file (renderUI)", "Save file as ...", filetype = input$filetype)
        })
        
        observe({
            shinyFileChoose(input = input, id = "loadFileUI", updateFreq = 0, session = session, roots = volumes, filetypes = input$filetype)
        })
        
        output$loadFileOutput <- renderUI({
          shinyFilesButton("loadFileUI", "Load a file (renderUI)", "Load a file", multiple = TRUE)
        })
        
        output$selectDirOutput <- renderUI({
            shinyDirButton("selectDirUI", "Folder select (renderUI)", "Please select a folder")
        })
    }
)
```

**Comment by thomasp85** [comment]
I think this sensible - can I get you to fix the last documentation warnings? Then I'll merge it

**Comment by vnijs** [comment]
Addressed #75 by adding `shiny*Link`s. Check are failing due to documentation warnings. I haven't used cross-links much before so I'm not sure where to make changes.

An important change in this update is putting `fileGet <- do.call(fileGetter, list(...))` *inside* the observer in `shinyFileChoose`. This makes it much easier and cleaner to allow dependencies with, e.g., a filetype dropdown and adjust the files that are shown in the file choose. The alternative would be to put `shinyFileChoose` inside an observer which is not ideal. 

@thomasp85 I have about 90% of the code changes required to use `shinyFiles` in [`radiant.data`](https://github.com/radiant-rstats/radiant.data) done and it is working great! I would very much like to push the updates to CRAN in the next week or two. If you could take a look at the changes and merge (if OK) that would be great.

@keqiang It seems this PR address #44 as well so ... is localStorage (PR 68) still needed?

```r
library(shiny)
library(shinyFiles)

# options(shiny.trace = TRUE)

shinyApp(
    ui = fluidPage(
        sidebarLayout(
            sidebarPanel(
                uiOutput("shinyFilesOutput"),
                selectInput("filetype", "Choose file type", c("csv", "txt", "rda", "R")),
                textInput("filename", "Initial filename", value = "", placeholder = "provide an initial filename")
            ),
            mainPanel()
        )
    ),
    server = function(input, output, session) {

        volumes <- c(Desktop = normalizePath("~/Desktop"), Project = getwd())
        shinyFileSave(input, "saveFileUI", roots = volumes, session = session)
        shinyFileChoose(input = input, id = "loadFileUI", updateFreq = 0, session = session, roots = volumes, filetypes = function() input$filetype)
        
        output$shinyFilesOutput <- renderUI({
          tagList(
            shinySaveButton("saveFileUI", "Save file (renderUI)", "Save file as ...", filename = input$filename, filetype = input$filetype, icon = icon("download")),
            shinyFilesButton("loadFileUI", "Load a file (renderUI)", "Load a file", multiple = TRUE, icon = icon("upload")),
          )
        })
    }
)
```

**Comment by thomasp85** [comment]
I'm merging and fixing in master as it is just doc issues...

Can I get you to go through the issue list and mark all of the issues you have addressed for closing - I've lost the overview :-)

**Pull request merged**
