### PR TITLE
Correct bug on getVolumes() for windows

### PR DESCRIPTION
**Pull request by olivier6088**
PR for issue #40 shinyDirChoose() with getVolumes() only select C:/ in windows 7
https://github.com/thomasp85/shinyFiles/issues/40

### CODE REVIEW

**Comment by thomasp85** [comment]
Have you tested this on other windows versions?

**Comment by olivier6088** [comment]
No only windows 7 Pro

image

**Comment by thomasp85** [comment]
Do you have possibilities to test on additional systems so we are sure that this won't break the package for other users

**Comment by olivier6088** [comment]
Unfortunately no I only have my poor old laptop...

**Comment by SamGG** [comment]
Hi,
Sorry to get in the discussion. It's not clear to me what the original trouble is. I have got a Win7 Pro also, and in my hand a call to getVolumes returns the correct list of volumes. What I noticed is that ```getVolumes()``` returns a **function**. So in order to get the correct list of volumes I had to add extra paranthesis, ie ```getVolumes()()```. Just try this on the R console, and let us know.
https://github.com/thomasp85/shinyFiles/blob/d2d2516d410d44db6fe8d15b3ca657a601239772/R/aaa.R#L56-L87
HTH

**Comment by thomasp85** [comment]
Thanks for this @SamGG - we definitely needs to get this tested on multiple systems to make sure where the problem is.

It is true the `getVolumes` returns a function - this is how it can respond to changes in the file system dynamically...

**Comment by olivier6088** [comment]
Hi guys,

Get back to the description of the issue and you will understand: https://github.com/thomasp85/shinyFiles/issues/40
The problem comes from the value returned by getVolumes() or getVolumes()() (it returns a character vector), more specifically it comes from the parenthesis (, ) on the volumes' names.

**Comment by thomasp85** [comment]
I'm aware of that. But this Is no longer a general Windows 7 problem so we need to be careful not to introduce new problem with the fix. @samgg can you test the proposed solution on your system and see if it works?

**Comment by SamGG** [comment]
Hi,
Currently the example given in the release of shinyFiles is working in my case (sessinInfo() below).
```r
runApp(system.file(package = "shinyFiles", "example"))
```
The volume content is not refreshed when the volume is an unmounted DVD.
Concerning the patch, Name and Caption is returning the same information in my case, ie the letter of the volume. The volumeName helps the user to identify the right volume quickly. So I am not in favor of removing the volumeName information. Finally, the only difference in the patch concerns the removal of the parenthesis encapsulation https://github.com/thomasp85/shinyFiles/pull/41/commits/548c955b44f2c2c4986494e5e27457a5b614dde1#diff-f1550339dce6c49372977f30133255fcL77. While I don't see how it could harm currently, I am thinking of another issue: volumeName could contain some characters that should be escaped. @olivier6088 could you please look at those volume names by running ```r system('wmic logicaldisk get VolumeName', intern=T)```?
Best.

```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.13.2     shinyFiles_0.6.0

loaded via a namespace (and not attached):
 [1] R6_2.1.2        rsconnect_0.4.3 htmltools_0.3.5 tools_3.2.3     Rcpp_0.12.6     RJSONIO_1.3-0  
 [7] jsonlite_1.0    digest_0.6.10   xtable_1.8-2    httpuv_1.3.3    mime_0.5      
```

**Comment by olivier6088** [comment]
Here for you @SamGG 

```r
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.0
> system('wmic logicaldisk get VolumeName', intern=T)
[1] "VolumeName  \r" "            \r" "            \r" "            \r" "\r"       
```

**Comment by thomasp85** [comment]
Wonder if this is somehow related to French locale?

**Comment by olivier6088** [comment]
Humm maybe

**Comment by thomasp85** [comment]
@samgg can you share your volume names too. I'm away from a Windows system so don't know the expected format at the moment

**Comment by thomasp85** [comment]
My best guess is we need to check for empty voluneNames before assembling them

**Comment by SamGG** [comment]
Here it is. Switching to French locales ```Sys.setlocale("LC_ALL","French")```didn't change the result in my case.
```r
> getVolumes()()
          (C:)           (D:)  HP_TOOLS (E:)           (F:) XXXXXXXXX (G:)           (X:) 
          "C:"           "D:"           "E:"           "F:"           "G:"           "X:" 
> system('wmic logicaldisk get Caption', intern=T)
[1] "Caption  \r" "C:       \r" "D:       \r" "E:       \r" "F:       \r" "G:       \r" "X:       \r"
[8] "\r"         
> system("wmic logicaldisk get name", intern = T)
[1] "Name  \r" "C:    \r" "D:    \r" "E:    \r" "F:    \r" "G:    \r" "X:    \r" "\r"      
> system('wmic logicaldisk get VolumeName', intern=T)
[1] "VolumeName  \r" "            \r" "            \r" "HP_TOOLS    \r" "            \r" "XXXXXXXXX   \r"
[7] "            \r" "\r"            
```

**Comment by SamGG** [comment]
I have just rename the HP_TOOLS volume to an empty name (ie no character at all). The example is still working with French locales. @olivier6088 in your proposal concerning the example/server.R, I think you should add an extra () https://github.com/thomasp85/shinyFiles/pull/41/commits/548c955b44f2c2c4986494e5e27457a5b614dde1#diff-b58bda25f91805b86bc6a57f9da7afaeR5

**Comment by thomasp85** [comment]
The example is fine. It is intended to passed in as a function

**Comment by SamGG** [comment]
OK for the call of getVolumes(). I agree the assembling of empty has to check. Let me know. @olivier6088 thanks.

**Comment by olivier6088** [comment]
So,
I've re-run your example @thomasp85 in `inst`:

* Making sure original code is running:
```r
> library(shinyFiles)
Warning message:
package ‘shinyFiles’ was built under R version 3.3.1 
> getVolumes
function (exclude) 
{
    if (missing(exclude)) 
        exclude <- NULL
    function() {
        osSystem <- Sys.info()["sysname"]
        if (osSystem == "Darwin") {
            volumes <- list.files("/Volumes/", full.names = T)
            names(volumes) <- basename(volumes)
        }
        else if (osSystem == "Linux") {
            volumes <- c(Computer = "/")
            media <- list.files("/media/", full.names = T)
            names(media) <- basename(media)
            volumes <- c(volumes, media)
        }
        else if (osSystem == "Windows") {
            volumes <- system("wmic logicaldisk get Caption", 
                intern = T)
            volumes <- sub(" *\\r$", "", volumes)
            keep <- !tolower(volumes) %in% c("caption", "")
            volumes <- volumes[keep]
            volNames <- system("wmic logicaldisk get VolumeName", 
                intern = T)
            volNames <- sub(" *\\r$", "", volNames)
            volNames <- volNames[keep]
            volNames <- paste0(volNames, " (", volumes, ")")
            names(volumes) <- volNames
        }
        else {
            stop("unsupported OS")
        }
        if (!is.null(exclude)) {
            volumes <- volumes[!names(volumes) %in% exclude]
        }
        volumes
    }
}
<environment: namespace:shinyFiles>
```

* Case 1: use getVolumes():

```r
library(shiny)
library(shinyFiles)

shinyServer(function(input, output, session) {
    volumes <- getVolumes() # c('R Installation'=R.home())
    shinyFileChoose(input, 'file', roots=volumes, session=session, restrictions=system.file(package='base'))
    shinyDirChoose(input, 'directory', roots=volumes, session=session, restrictions=system.file(package='base'))
    shinyFileSave(input, 'save', roots=volumes, session=session, restrictions=system.file(package='base'))
    output$filepaths <- renderPrint({parseFilePaths(volumes, input$file)})
    output$directorypath <- renderPrint({parseDirPath(volumes, input$directory)})
    output$savefile <- renderPrint({parseSavePath(volumes, input$save)})
})
```

**Result is impossible to select other volumes:**

case_getvolumes


* Case 2: use getVolumes()():

```r
library(shiny)
library(shinyFiles)

shinyServer(function(input, output, session) {
    volumes <- getVolumes()() # c('R Installation'=R.home())
    shinyFileChoose(input, 'file', roots=volumes, session=session, restrictions=system.file(package='base'))
    shinyDirChoose(input, 'directory', roots=volumes, session=session, restrictions=system.file(package='base'))
    shinyFileSave(input, 'save', roots=volumes, session=session, restrictions=system.file(package='base'))
    output$filepaths <- renderPrint({parseFilePaths(volumes, input$file)})
    output$directorypath <- renderPrint({parseDirPath(volumes, input$directory)})
    output$savefile <- renderPrint({parseSavePath(volumes, input$save)})
})
```

**Result is impossible to select other volumes:**

case_getvolumes

**Comment by SamGG** [comment]
In the getVolumes code I replaced line
```r
            volNames <- paste0(volNames, ' (', volumes, ')')
```
with
```r
            volNames <- paste0(volNames, ifelse(volNames == "", "", " "))
            volNames <- paste0(volNames, '(', volumes, ')')
```
@olivier6088 could you try it please?
If this does not do the job, then do whatever could correct this bug guys.

**Comment by thomasp85** [comment]
@olivier6088 What do you get when you simply call `getVolumes()()` from the R console?

**Comment by olivier6088** [comment]
@SamGG yes this substitution works on my computer ! :+1: 

But there is another issue (either in the original code, my proposition of correction and yours) in the path returned, it has double slashes...

double_slash_issue

**Comment by thomasp85** [comment]
Hmm, that should have been fixed. Let's see if I forgot to push the changes

**Comment by SamGG** [comment]
I have got the same double slashes output with the version I retrieved this morning from Github.

**Comment by thomasp85** [comment]
Ok - ignore that for know. I'll fix this manually and attribute you in the news

**Comment by SamGG** [comment]
@olivier6088 congrat
@thomasp85 let us know in order to test it if needed

**Comment by olivier6088** [comment]
@SamGG and @thomasp85 it was nice to work with you guys !

**Comment by thomasp85** [comment]
Fixed in 8202f00 - thanks

**Pull request closed without merging**
