### PR TITLE
Allow dir chooser to disable creating new directories

### PR DESCRIPTION
**Pull request by dipterix**
Related to #143

### CODE REVIEW

**Comment by vnijs** [comment]
Looks pretty good @dipterix! Haven't tested this yet but I think that in your setup the user would always see a notification, even when not trying to create a new directory. How about changing up the nesting of the if-else statements as shown the below? Can you test and submit updates as needed?

Thanks

```
if (!identical(createDir, lastDirCreate)) {
  if (writable) {
    dirCreate(createDir$name, createDir$path, createDir$root)
    lastDirCreate <<- createDir
  } else {
    shiny::showNotification(shiny::p('Creating directories has been disabled.'), type = 'error')
  }
}
```

**Comment by vnijs** [comment]
Also, please ensure that `showNotification`, and `p`, are properly imported from the `shiny` package.

**Comment by dipterix** [comment]
Sure, I've switched two if statements and that resolves the problem you mentioned. 
As for `showNotification` and `p`, since your DESCRIPTION file has already included `shiny` package, and I used `shiny::xxx` prefix instead of directly calling the names, there's no need to import those functions in NAMESPACE file.

**Comment by vnijs** [comment]
Thanks @dipterix. shinyFiles does not import all functions from the shiny package and so these two will most likely need to be explicitly imported. Please run _Build > Check_ in Rstudio to confirm and update as needed.

**Comment by dipterix** [comment]
Actually I did check `as-cran`, it passed the check. The reason is because I used `shiny::p` instead of `p` directly. If I use `p` directly, it'll require something like `importFrom(shiny,p)` in NAMESPACE file. However, by using `shiny::p` there's no need to do so.

In [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) chapter 1.5.1:

> If a package only needs a few objects from another package it can use a fully qualified variable reference in the code instead of a formal import. A fully qualified reference to the function f in package foo is of the form foo::f. This is slightly less efficient than a formal import and also loses the advantage of recording all dependencies in the NAMESPACE file (but they still need to be recorded in the DESCRIPTION file). Evaluating foo::f will cause package foo to be loaded, but not attached, if it was not loaded already—this can be an advantage in delaying the loading of a rarely used package.

I did that because I was not sure if you want to make full reference to shiny package. If you want to change `shiny::p` to `p` and make full reference, I can do it.

**Comment by vnijs** [comment]
Perhaps something has changed with how CRAN evaluates the use of :: in functions. It used to be that even if you used that in a function you still had to explicitly import somewhere to pass all CRAN checks. I did add explicit imports out of habit but you are right that it (now) seems to pass the checks either way.

FYI I changed a few minor things after your PR:

1. Added the option to restrict creating directories also for save file buttons
2. Changed "writable" argument to "allowDirCreate" which is more explicit about what it does (not) allow
3. Equate `lastDirCreate` and `createDir` after an attempt by the user to create directory (i.e., after the notification). Without this you get 2 notifications the first time a user tries to create a directory and then more notifications every time a user clicks on the choose dir button. See code snippet below.

Please try this out and let me know if you run into an edge cases.

```
    if (!identical(createDir, lastDirCreate)) {
      if (allowDirCreate) {
        dirCreate(createDir$name, createDir$path, createDir$root)
        lastDirCreate <<- createDir
      } else {
        shiny::showNotification(shiny::p('Creating directories has been disabled.'), type = 'error')
        lastDirCreate <<- createDir
      }
    }
```

**Comment by dipterix** [comment]
That works great! Thanks :)

**Comment by xuefenfei712** [comment]
Thankyou so much for your shinyfiles, it is quite useful for me, I also have this problem in my Mac, 
I use The_dir <- reactive({
    shinyDirChoose(input, 'sheets_dir', roots = Theroots(), session = session)
    parseDirPath(roots = Theroots(), input$sheets_dir)
  })
I can create a new folder after click on the "+" button, however it collapse after it.  you post a new code for it, I donot know how to use it, please specify
thankyou
xue

**Pull request merged**
