### PR TITLE
Partial for #79

### PR DESCRIPTION
**Pull request by vnijs**
**Close modal on Escape:** lines 481-488 work when you first open the modal but if you close-and-reopen you get the error below. Also, once you start interacting with the modal Escape no longer closes the modal. Any suggestions?

image

**Select file on double-click:** lines 542-546 works great!

**Open folder on enter:** lines 547-553 do not work. Any suggestions?

**Save file on Enter:** lines 1108-1114 do not work. Any suggestions?

Changing `objSize` to `Object.keys(oldFiles).length === 0`. On repreated open and close of the modal, previously you would get the error below. `Object...` resolves the issue.

image

### CODE REVIEW

**Comment by thomasp85** [comment]
I think we should delay this until after a CRAN release as I don't have the mental capacity right now to understand the best way of achieving this - Are you ok with that?

**Comment by vnijs** [comment]
I commented out the things that don't work (yet) already. If you merge this PR I still get "Select file on double-click: lines 542-546 works great!" which I would really like to keep in the release if possible. Sound ok?

**Comment by thomasp85** [comment]
That sounds fine, if you'd be willing to split out the PR in two, as I rather not have out-commented code merged in

**Comment by vnijs** [comment]
Done. Thanks @thomasp85 and @thercast for pulling this together on such short notice. *Really* helps me out a lot.

With the release of ggplot2 3.0.0 I'm now also looking forward to the first CRAN version of `patchwork` @thomasp85 :)

**Comment by thomasp85** [comment]
Haha - I literally got this yesterday https://github.com/thomasp85/patchwork/pull/65

**Comment by thomasp85** [comment]
I'll submit the update to cran today as v0.7.0

**Pull request merged**
